services:
  tiago_simulation:
    build:
      context: .
      dockerfile: Dockerfile
    image: tiago_simulation_custom:latest
    container_name: tiago_simulation_container
    network_mode: host
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - LC_NUMERIC=C
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ~/.Xauthority:/root/.Xauthority:ro
      - ../:/tiago_workspace
      - /home/par1adux/dataset:/dataset
    working_dir: /tiago_workspace
    entrypoint: []
    stdin_open: true
    tty: true
