services:
  tiago_simulation:
    image: palroboticssl/tiago_tutorials:noetic
    container_name: tiago_simulation_container
    network_mode: host
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - LC_NUMERIC=C
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ~/.Xauthority:/root/.Xauthority:ro
      - ../:/tiago_workspace
    working_dir: /tiago_workspace
    entrypoint: []
    stdin_open: true
    tty: true
